name: Build Docker Image
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Determine latest version
        id: latest_version
        uses: flownative/action-git-latest-release@master

      - run: |
          sudo chmod -R ugo+rwX . && shopt -s dotglob && rm -rf *

      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.latest_version.outputs.tag }}
          fetch-depth: 100
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Google Artifacts Registry
        uses: docker/login-action@v1
        with:
          registry: europe-docker.pkg.dev/flownative/docker
          username: '_json_key'
          password: ${{ secrets.GOOGLE_ARTIFACTS_PASSWORD_DOCKER }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            europe-docker.pkg.dev/flownative/docker/bash-library:${{ steps.latest_version.outputs.version }}
            europe-docker.pkg.dev/flownative/docker/bash-library:latest
