name: Build Docker Image
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Determine latest version
        id: latest_version
        uses: flownative/action-git-latest-release@v1

      - run: |
          sudo chmod -R ugo+rwX . && shopt -s dotglob && rm -rf *

      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.latest_version.outputs.tag }}
          fetch-depth: 100

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          flavor: |
            latest=true
          images: |
            europe-docker.pkg.dev/flownative/docker/bash-library
          tags: |
            type=semver,pattern={{major}},value=${{ steps.latest_version.outputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.latest_version.outputs.version }}
            type=semver,pattern={{version}},value=${{ steps.latest_version.outputs.version }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Google Artifacts Registry
        uses: docker/login-action@v1
        with:
          registry: europe-docker.pkg.dev/flownative/docker
          username: '_json_key'
          password: ${{ secrets.GOOGLE_ARTIFACTS_PASSWORD_DOCKER }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
